In [1]:
import numpy as np
import torch
import math

In [2]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

In [3]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.5553, 0.1779],
        [0.2419, 0.3589]]) 



In [4]:
torch.rand(3,4,2) 

tensor([[[0.0835, 0.3536],
         [0.4103, 0.5858],
         [0.6048, 0.9276],
         [0.1979, 0.9297]],

        [[0.3671, 0.8877],
         [0.3201, 0.3493],
         [0.0595, 0.6767],
         [0.9492, 0.1711]],

        [[0.4025, 0.1656],
         [0.1364, 0.3969],
         [0.9291, 0.7793],
         [0.7086, 0.9648]]])

In [5]:
torch.randn(4,5)

tensor([[-1.1848,  0.4733,  0.0143,  1.0941, -0.6655],
        [ 0.2513,  0.4041, -1.4058,  0.5588,  0.5938],
        [-0.1059,  0.4276, -0.8348,  1.3807,  0.9695],
        [-0.6974, -1.9407,  0.3101,  1.1979, -0.1503]])

In [6]:
device = torch.device('cpu')
torch.randn((),device=device,dtype=float)

tensor(1.6520, dtype=torch.float64)

In [7]:
a = torch.randn((),device=device,requires_grad=True)

In [8]:
import torch
import math

x = torch.linspace(-math.pi,math.pi,2000,device = device,dtype=float)
y = torch.sin(x)

learning_rate = 0.000002
a = torch.randn((),device = device,dtype=float,requires_grad = True)
b = torch.randn((),device = device,dtype=float,requires_grad = True)
c = torch.randn((),device = device,dtype=float,requires_grad = True)
d = torch.randn((),device = device,dtype=float,requires_grad = True)

for t in range(2000):
    y_pred = a*x**3+b*x**2+c*x+d
    loss = (y_pred-y).pow(2).sum()
    loss.backward()
    if t%100 == 0:
        show = {'cost':loss.item(),'grad':[a.grad.item(),b.grad.item(),c.grad.item(),d.grad.item()]}
        print(show)
    with torch.no_grad():
        a -= learning_rate*a.grad
        b -= learning_rate*b.grad
        c -= learning_rate*c.grad
        d -= learning_rate*d.grad
        
        a.grad = None
        b.grad = None
        c.grad = None
        d.grad = None
        
        

{'cost': 112089.02572571824, 'grad': [344091.3473502386, -6718.8156249826725, 44536.62760641865, -475.81112918903085]}
{'cost': 2087.5910871926367, 'grad': [406.14951735974785, -80.98330733644184, -2855.3559368576553, 469.4221956026745]}
{'cost': 921.1639734917906, 'grad': [268.4515130912258, -57.29095077910829, -1887.2966454482275, 332.0894190569188]}
{'cost': 409.4915517445446, 'grad': [177.4376474689688, -40.530076343189464, -1247.4411970649164, 234.93430156253515]}
{'cost': 184.9090719583353, 'grad': [117.2804666912929, -28.672714731484596, -824.517726923199, 166.20260352593777]}
{'cost': 86.2713922287342, 'grad': [77.51854278687881, -20.284308450636047, -544.9791810709462, 117.57885176868167]}
{'cost': 42.917239188621174, 'grad': [51.23721490313254, -14.349989987824713, -360.2133684973209, 83.18032383339948]}
{'cost': 23.845876684892076, 'grad': [33.866118952306195, -10.151798527013865, -238.08922496673375, 58.84532948698307]}
{'cost': 15.448511415892106, 'grad': [22.3843941373424

In [9]:
import torch
import math

x = torch.linspace(-math.pi,math.pi,2000)
y = torch.sin(x)

p = torch.tensor([1, 2, 3])
xx = x.unsqueeze(-1).pow(p)

loss_fn = torch.nn.MSELoss(reduction='sum')

model  = torch.nn.Sequential(
    torch.nn.Linear(3,1),
    torch.nn.Flatten(0,1)
)

learning_rate = 1e-6


for t in range(3000):
    y_pred = model(xx)
    loss= loss_fn(y_pred,y)
    if t % 100 == 99:
        print(t, loss.item())
    model.zero_grad()
    loss.backward()
    with torch.no_grad():
        for param in model.parameters():
            param -= learning_rate*param.grad
            

99 1080.642333984375
199 727.4095458984375
299 490.95538330078125
399 332.5627746582031
499 226.38375854492188
599 155.1526336669922
699 107.32917022705078
799 75.19490814208984
899 53.58453369140625
999 39.038944244384766
1099 29.23948097229004
1199 22.631553649902344
1299 18.17142105102539
1399 15.157968521118164
1499 13.119929313659668
1599 11.74011516571045
1699 10.805007934570312
1799 10.170573234558105
1899 9.739668846130371
1999 9.446674346923828
2099 9.247236251831055
2199 9.111322402954102
2299 9.01858901977539
2399 8.955249786376953
2499 8.911934852600098
2599 8.882282257080078
2699 8.861959457397461
2799 8.84801197052002
2899 8.838430404663086
2999 8.831843376159668


In [10]:
import torch 
import math

x = torch.linspace(-math.pi,math.pi,2000)
y= torch.sin(x)

p= torch.tensor([1,2,3])
xx = x.unsqueeze(-1).pow(p)

model = torch.nn.Sequential(
torch.nn.Linear(3,1),
    torch.nn.Flatten(0,1)
)

learning_rate = 0.001
loss_fn = torch.nn.MSELoss(reduction='sum')
optimizer = torch.optim.RMSprop(model.parameters(),lr = learning_rate)

for t in range(2000):
    y_pred= model(xx)
    
    loss = loss_fn(y_pred,y)
    if t%100==0:
        print(t,loss.item())
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

0 20247.02734375
100 3078.748291015625
200 1795.03759765625
300 1541.400146484375
400 1327.697021484375
500 1117.6881103515625
600 923.993408203125
700 750.7020263671875
800 598.0798950195312
900 465.39141845703125
1000 351.78729248046875
1100 256.4897155761719
1200 178.66204833984375
1300 117.57154083251953
1400 72.358642578125
1500 41.059776306152344
1600 22.12139320373535
1700 12.713974952697754
1800 9.494978904724121
1900 8.934830665588379
